// Generated by dts-bundle v0.3.0

declare module 'cu-components' {
    var _default: {
        UnitFrame: __React.ClassicComponentClass<any>;
        UnitFrameEffects: __React.ClassicComponentClass<any>;
        UnitFrameHealthBar: __React.ClassicComponentClass<any>;
        UnitFrameHealthText: __React.ClassicComponentClass<any>;
        UnitFrameName: __React.ClassicComponentClass<any>;
        UnitFramePortrait: __React.ClassicComponentClass<any>;
        UnitFrameStaminaBar: __React.ClassicComponentClass<any>;
        UnitFrameStaminaText: __React.ClassicComponentClass<any>;
    };
    export default _default;
}

