// Generated by dts-bundle v0.3.0
// Dependencies for this module:
//   ../../src/tsd/react/react.d.ts

declare module 'cu-components' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    import UnitFrame from '__cu-components/unitframe/UnitFrame';
    import Effects from '__cu-components/unitframe/components/Effects';
    import HealthBar from '__cu-components/unitframe/components/HealthBar';
    import HealthText from '__cu-components/unitframe/components/HealthText';
    import Name from '__cu-components/unitframe/components/Name';
    import Portrait from '__cu-components/unitframe/components/Portrait';
    import StaminaBar from '__cu-components/unitframe/components/StaminaBar';
    import StaminaText from '__cu-components/unitframe/components/StaminaText';
    export { UnitFrame, Effects, HealthBar, HealthText, Name, Portrait, StaminaBar, StaminaText };
}

declare module '__cu-components/unitframe/UnitFrame' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    import * as React from 'react';
    const UnitFrame: React.ClassicComponentClass<any>;
    export default UnitFrame;
}

declare module '__cu-components/unitframe/components/Effects' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    import * as React from 'react';
    const Effects: React.ClassicComponentClass<any>;
    export default Effects;
}

declare module '__cu-components/unitframe/components/HealthBar' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    import * as React from 'react';
    const HealthBar: React.ClassicComponentClass<any>;
    export default HealthBar;
}

declare module '__cu-components/unitframe/components/HealthText' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    import * as React from 'react';
    const HealthText: React.ClassicComponentClass<any>;
    export default HealthText;
}

declare module '__cu-components/unitframe/components/Name' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    import * as React from 'react';
    const Name: React.ClassicComponentClass<any>;
    export default Name;
}

declare module '__cu-components/unitframe/components/Portrait' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    import * as React from 'react';
    const Portrait: React.ClassicComponentClass<any>;
    export default Portrait;
}

declare module '__cu-components/unitframe/components/StaminaBar' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    import * as React from 'react';
    const StaminaBar: React.ClassicComponentClass<any>;
    export default StaminaBar;
}

declare module '__cu-components/unitframe/components/StaminaText' {
    /**
      * This Source Code Form is subject to the terms of the Mozilla Public
      * License, v. 2.0. If a copy of the MPL was not distributed with this
      * file, You can obtain one at http://mozilla.org/MPL/2.0/.
      */
    import * as React from 'react';
    const StaminaText: React.ClassicComponentClass<any>;
    export default StaminaText;
}

